apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositevms.compute.platform.example.org
spec:
  group: compute.platform.example.org
  names:
    kind: CompositeVM
    plural: compositevms
    singular: compositevm
    shortNames: [cvm]
  claimNames: null
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                nic:
                  type: string
            spec:
              type: object
              properties:
                vnetName:
                  type: string
                vmSize:
                  type: string
                subnetName:
                  type: string
                subnetId:
                  type: string
                public:
                  type: boolean
                publicIPName:
                  type: string
                publicIPAddressId:
                  type: string
                sshKey:
                  type: string
                NICName:
                  type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
