apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-compositevm-binding
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: crossplane-compositevm-permissions
  apiGroup: rbac.authorization.k8s.io
