{{- range $k, $s := .Values.platform.subnets }}
{{- if $s.create }}
---
apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ $s.nsg }}
spec:
  forProvider:
    resourceGroupName: {{ $.Values.resourceGroup }}
    location: {{ $.Values.location }}
    securityRule:
      - name: Allow-SSH
        priority: 1000
        direction: Inbound
        access: Allow
        protocol: Tcp
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
      - name: Allow-HTTP
        priority: 1001
        direction: Inbound
        access: Allow
        protocol: Tcp
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
      - name: Allow-HTTPS
        priority: 1002
        direction: Inbound
        access: Allow
        protocol: Tcp
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
  providerConfigRef:
    name: {{ $.Values.providerConfig }}
{{- end }}
{{- end }}
